# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Kotlin code style
kotlin.code.style=official

# Allow KSP generated Kotlin sources with built-in Kotlin
android.disallowKotlinSourceSets=false

# Suppress warning for experimental project option
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE